//====================================================================================================================================================
// Copyright 2023 Lake Orion Robotics FIRST Team 302
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
// OR OTHER DEALINGS IN THE SOFTWARE.
//====================================================================================================================================================
//==============================================================
// This file is auto generated by FRCrobotCodeGen302.exe Version $CODE_GENERATOR_VERSION$
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated, unless the changes are delimited by:
//  //========= Hand modified code start section x ========
//                    Your hand written code goes here
//	//========= Hand modified code end section x ========
//==============================================================

#pragma once

// C++ Includes
#include <string>

// FRC includes

// Team 302 includes
#include <mechanisms/base/StateMgr.h>
#include <mechanisms/ActiveIntake/ActiveIntake.h>
#include <mechanisms/StateStruc.h>

//========= Hand modified code start section 0 ========
#include <robotstate/IRobotStateChangeSubscriber.h>
//========= Hand modified code end section 0 ========

// Third Party Includes

//========= Hand modified code start section 1 ========

//========= Hand modified code end section 1 ========

class ActiveIntakeStateMgr : public StateMgr
    //========= Hand modified code start section 2 ========
    ,
                             public IRobotStateChangeSubscriber
//========= Hand modified code end section 2 ========
{
public:
    /// @enum the various states of the Intake
    enum ACTIVEINTAKE_STATE
    {
        OFF,
        INTAKE,
        HOLD,
        PLACE
    };

    const std::string m_ActiveIntakeXMLOffString{"OFF"};
    const std::string m_ActiveIntakeXMLIntakeString{"INTAKE"};
    const std::string m_ActiveIntakeXMLHoldString{"HOLD"};
    const std::string m_ActiveIntakeXMLPlaceString{"PLACE"};
    const std::map<const std::string, ACTIVEINTAKE_STATE> m_ActiveIntakeXmlStringToStateEnumMap{
        {m_ActiveIntakeXMLOffString, ACTIVEINTAKE_STATE::OFF},
        {m_ActiveIntakeXMLIntakeString, ACTIVEINTAKE_STATE::INTAKE},
        {m_ActiveIntakeXMLHoldString, ACTIVEINTAKE_STATE::HOLD},
        {m_ActiveIntakeXMLPlaceString, ACTIVEINTAKE_STATE::PLACE}};

    /// @brief  Find or create the state manmanager
    static ActiveIntakeStateMgr *GetInstance();

    /// @brief  Get the current Parameter parm value for the state of this mechanism
    /// @param PrimitiveParams* currentParams current set of primitive parameters
    /// @returns int state id - -1 indicates that there is not a state to set
    int GetCurrentStateParam(
        PrimitiveParams *currentParams) override;

    void CheckForStateTransition() override;
    //========= Hand modified code start section 3 ========
    void CheckForSensorTransitions() override;
    void CheckForGamepadTransitions() override;

    // RobotState override
    void Update(RobotStateChanges::StateChange change, int value) override;
    //========= Hand modified code end section 3 ========

private:
    ActiveIntakeStateMgr();
    ~ActiveIntakeStateMgr() = default;

    //========= Hand modified code start section 4 ========

    //========= Hand modified code end section 4 ========

    ActiveIntake *m_activeIntake;

    //========= Hand modified code start section 5 ========
    ACTIVEINTAKE_STATE m_currentState;
    ACTIVEINTAKE_STATE m_targetState;
    ACTIVEINTAKE_STATE m_prevState;

    bool m_followOtherMechs = false;
    const double m_floorThreshold = 15.0;
    const double m_protectThreshold = 3.0;
    //========= Hand modified code end section 5 ========

    static ActiveIntakeStateMgr *m_instance;

    const StateStruc m_off = {ACTIVEINTAKE_STATE::OFF, "OFF", StateType::GRABBER_STATE, true};
    const StateStruc m_intake = {ACTIVEINTAKE_STATE::INTAKE, "INTAKE", StateType::GRABBER_STATE, false};
    const StateStruc m_hold = {ACTIVEINTAKE_STATE::HOLD, "HOLD", StateType::GRABBER_STATE, false};
    const StateStruc m_place = {ACTIVEINTAKE_STATE::PLACE, "PLACE", StateType::GRABBER_STATE, false};
};
// const StateStruc m_openState = {ActiveIntake_STATE::OPEN, "OPEN", StateType::ActiveIntake_STATE, false};
// const StateStruc m_grabState = {ActiveIntake_STATE::GRAB, "GRAB", StateType::ActiveIntake_STATE, true};
